spring:
  application:
    name: farm-planner
  main:
    web-application-type: servlet

server:
  port: 8080

app:
  nominatimUserAgent: "FarmPlanner/0.1 (your-real-email@example.com)"
  worcesterParcelsLayerUrl: "https://wcg-gisweb.co.worcester.md.us/arcgis/rest/services/Parcels/MapServer/5"

  # (optional; only if you added security)
  auth:
    username: user
    password: user
  cors:
    allowedOrigins:
      - http://localhost:5173
      - http://localhost:3000
