server:
  port: 8080

app:
  # Required by Nominatim; use a real email
  nominatimUserAgent: "FarmPlanner/0.1 (younis@zipcode.rock)"
  # Worcester County Parcels layer (polygon parcels with Acres + ACCTID)
  worcesterParcelsLayerUrl: "https://wcg-gisweb.co.worcester.md.us/arcgis/rest/services/Parcels/MapServer/5"

spring:
  application:
    name: farm-planner
